var nombre = `cinthia`;
var apellido = `burack`;
var edad = 29;
var fechaDeNacimiento = `29/10/1987`;
var direccion = `sarmiento 4481`;
console.log(nombre);
console.log(apellido);
console.log(edad);
console.log(fechaDeNacimiento);
console.log(direccion);